import React from "react";
import styles from "./Footer.module.scss";
const Footer = () => {
    return (React.createElement("footer", { className: styles.footer },
        React.createElement("div", { className: styles.footerContent },
            React.createElement("div", { className: styles.footerColumn },
                React.createElement("h4", null, "Discover Patagonia"),
                React.createElement("p", { className: styles.discover }, "Discover the best of Patagonia, Argentina through unique experiences and unforgettable adventures.")),
            React.createElement("div", { className: styles.footerColumn },
                React.createElement("h4", null, "Quick Links"),
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("a", { href: "/" }, "Home")),
                    React.createElement("li", null,
                        React.createElement("a", { href: "/destinations" }, "Destinations")),
                    React.createElement("li", null,
                        React.createElement("a", { href: "/experiences" }, "Experiences")),
                    React.createElement("li", null,
                        React.createElement("a", { href: "/contact" }, "Contact Us")))),
            React.createElement("div", { className: styles.footerColumn },
                React.createElement("h4", null, "Contact Us"),
                React.createElement("p", null, "Email: discoverpatagonia@gmail.com"),
                React.createElement("p", null, "Phone: +49 123458783 "),
                React.createElement("p", null, "Location: Singen, Germany")),
            React.createElement("div", { className: styles.footerColumn },
                React.createElement("h4", null, "Follow Us"),
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("a", { href: "https://instagram.com" }, "Instagram")),
                    React.createElement("li", null,
                        React.createElement("a", { href: "https://facebook.com" }, "Facebook")),
                    React.createElement("li", null,
                        React.createElement("a", { href: "https://twitter.com" }, "Twitter"))))),
        React.createElement("div", { className: styles.footerBottom },
            "\u00A9 2024 Explore Argentina. All rights reserved. |",
            " ",
            React.createElement("a", { href: "/privacy" }, "Privacy Policy"))));
};
export default Footer;
