import React from "react";
import styles from "./acommodation.module.scss";
const Accommodation = () => {
    return (React.createElement("div", { className: styles.accommodationPage },
        React.createElement("header", { className: styles.hero },
            React.createElement("div", { className: styles.heroText },
                React.createElement("h1", null, "Your Ideal Stay Awaits"),
                React.createElement("p", null, "Discover carefully curated accommodations for every type of traveler. Whether you\u2019re looking for rustic charm or modern luxury, we\u2019ve got you covered."),
                React.createElement("button", { className: styles.exploreButton }, "Browse Accommodations"))),
        React.createElement("section", { className: styles.features },
            React.createElement("h2", null, "Why Choose Us?"),
            React.createElement("div", { className: styles.featuresGrid },
                React.createElement("div", { className: styles.featureItem },
                    React.createElement("img", { src: "/src/assets/images/habitacion.jpg", alt: "Tailored Options" }),
                    React.createElement("h3", null, "Tailored for You"),
                    React.createElement("p", null, "Enjoy accommodations that match your unique style, whether you\u2019re seeking an adventurous getaway or a relaxing retreat.")),
                React.createElement("div", { className: styles.featureItem },
                    React.createElement("img", { src: "/src/assets/images/rayentray.jpg", alt: "Global Network" }),
                    React.createElement("h3", null, "Extensive Options"),
                    React.createElement("p", null, "Access a wide range of accommodations, from boutique hotels to cozy chalets, all carefully selected for quality and comfort.")),
                React.createElement("div", { className: styles.featureItem },
                    React.createElement("img", { src: "/src/assets/images/familia2.jpg", alt: "Seamless Booking" }),
                    React.createElement("h3", null, "Seamless Booking"),
                    React.createElement("p", null, "Book with ease and confidence. Our streamlined process ensures a hassle-free experience from start to finish.")))),
        React.createElement("section", { className: styles.bookingSteps },
            React.createElement("h2", null, "How It Works"),
            React.createElement("ol", { className: styles.stepsList },
                React.createElement("li", null,
                    React.createElement("strong", null, "Step 1:"),
                    " Share your preferences and travel details through our form or directly with our team."),
                React.createElement("li", null,
                    React.createElement("strong", null, "Step 2:"),
                    " Receive a selection of handpicked accommodations tailored to your needs."),
                React.createElement("li", null,
                    React.createElement("strong", null, "Step 3:"),
                    " Choose your favorite and book in just a few clicks. It\u2019s that simple!"))),
        React.createElement("section", { className: styles.testimonials },
            React.createElement("h2", null, "What Our Guests Say"),
            React.createElement("div", { className: styles.testimonialCards },
                React.createElement("div", { className: styles.testimonialCard },
                    React.createElement("p", null, "\"The process was so simple and efficient. I found a beautiful eco-lodge that perfectly matched what I was looking for!\""),
                    React.createElement("h4", null, "- Emily R.")),
                React.createElement("div", { className: styles.testimonialCard },
                    React.createElement("p", null, "\"A seamless experience from start to finish. The accommodation options were fantastic, and the booking process was effortless.\""),
                    React.createElement("h4", null, "- John D.")),
                React.createElement("div", { className: styles.testimonialCard },
                    React.createElement("p", null, "\"Highly recommend! They found us a stunning villa with everything we wanted. It made our trip unforgettable.\""),
                    React.createElement("h4", null, "- Sarah L.")))),
        React.createElement("section", { className: styles.callToAction },
            React.createElement("h2", null, "Start Your Journey Today"),
            React.createElement("p", null, "Browse our exclusive range of accommodations and find the perfect place to stay. Your dream trip is just a few clicks away."),
            React.createElement("button", { className: styles.bookNowButton }, "Explore Accommodations"))));
};
export default Accommodation;
